### 1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: A)Rank, B) Name, C) Artist, D) Upload date, E) Views

In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\hp\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\hp\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\hp\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\hp\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
import selenium
import pandas as pd
from selenium import webdriver

import warnings
warnings.filterwarnings('ignore')

from selenium.webdriver.common.by import By
import time

In [3]:
driver = webdriver.Chrome()

In [4]:
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [5]:

Name = []
Artist = []
Upload_date = []
Views = []

In [6]:


names = driver.find_elements(By.XPATH, '//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[1]')
for i in names:
    Name.append(i.text)
    
    
    
artist_name = driver.find_elements(By.XPATH, '//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[2]')
for j in artist_name:
    Artist.append(j.text)
    
    
    
date = driver.find_elements(By.XPATH, '//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[4]')
for k in date:
    Upload_date.append(k.text)
    
    
    
view = driver.find_elements(By.XPATH, '//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[3]')
for l in view:
    Views.append(l.text)

In [7]:
print(len(Name))
print(len(Artist))
print(len(Upload_date))
print(len(Views))

30
30
30
30

In [8]:
df = pd.DataFrame({'Name': Name, 'Artist Name': Artist, 'Upload Date': Upload_date, 'Views': Views})
df

,Name,Artist Name,Upload Date,Views
0,"""Baby Shark Dance""[7]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",14.32
1,"""Despacito""[10]",Luis Fonsi,"January 12, 2017",8.41
2,"""Johny Johny Yes Papa""[18]",LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.89
3,"""Bath Song""[19]",Cocomelon - Nursery Rhymes,"May 2, 2018",6.66
4,"""Shape of You""[20]",Ed Sheeran,"January 30, 2017",6.23
5,"""See You Again""[23]",Wiz Khalifa,"April 6, 2015",6.22
6,"""Wheels on the Bus""[28]",Cocomelon - Nursery Rhymes,"May 24, 2018",6.01
7,"""Phonics Song with Two Words""[29]",ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.75
8,"""Uptown Funk""[30]",Mark Ronson,"November 19, 2014",5.18
9,"""Gangnam Style""[31]",Psy,"July 15, 2012",5.10
10,"""Learning Colors – Colorful Eggs on a Farm""[36]",Miroshka TV,"February 27, 2018",5.09
11,"""Dame Tu Cosita""[37]",Ultra Records,"April 5, 2018",4.59
12,"""Masha and the Bear – Recipe for Disaster""[38]",Get Movies,"January 31, 2012",4.57
13,"""Axel F""[39]",Crazy Frog,"June 16, 2009",4.45
14,"""Sugar""[40]",Maroon 5,"January 14, 2015",4.02
15,"""Baa Baa Black Sheep""[41]",Cocomelon - Nursery Rhymes,"June 25, 2018",4.01
16,"""Counting Stars""[42]",OneRepublic,"May 31, 2013",4.00
17,"""Lakdi Ki Kathi""[43]",Jingle Toons,"June 14, 2018",3.98
18,"""Roar""[44]",Katy Perry,"September 5, 2013",3.98
19,"""Waka Waka (This Time for Africa)""[45]",Shakira,"June 4, 2010",3.89
20,"""Sorry""[46]",Justin Bieber,"October 22, 2015",3.78
21,"""Shree Hanuman Chalisa""[47]",T-Series Bhakti Sagar,"May 10, 2011",3.77
22,"""Humpty the train on a fruits ride""[48]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.76
23,"""Thinking Out Loud""[49]",Ed Sheeran,"October 7, 2014",3.75
24,"""Perfect""[50]",Ed Sheeran,"November 9, 2017",3.70
25,"""Dark Horse""[51]",Katy Perry,"February 20, 2014",3.70
26,"""Let Her Go""[52]",Passenger,"July 25, 2012",3.64
27,"""Faded""[53]",Alan Walker,"December 3, 2015",3.60
28,"""Girls Like You""[54]",Maroon 5,"May 31, 2018",3.58
29,"""Lean On""[55]",Major Lazer Official,"March 22, 2015",3.57

### 2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.  You need to find following details:
 A) Series
 B) Place
 C) Date
 D) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\hp\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\hp\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\hp\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\hp\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
import selenium
import pandas as pd
from selenium import webdriver

import warnings
warnings.filterwarnings('ignore')

from selenium.webdriver.common.by import By
import time

from selenium.common.exceptions import NoSuchElementException

In [18]:
driver = webdriver.Chrome()

In [19]:
driver.get("https://www.bcci.tv/")

In [20]:
fixtures = driver.find_element(By.XPATH, '/html/body/header/div[3]/div[2]/ul/div[1]/a[2]')
fixtures.click()

In [23]:
more_search = driver.find_element(By.XPATH, '/html/body/section/div/div/div/div/div/div[2]/div[2]/div[2]/div/button')
more_search.click()

In [24]:
urls=[]

page_urls=driver.find_elements(By.XPATH, '//a[@class="match-btn match-card-btn ng-scope"]')
        
for url in page_urls:
    url = url.get_attribute('href')
    if url[0:4] == 'http':
        urls.append(url)

In [25]:
len(urls)

15

In [27]:
urls

['https://www.bcci.tv/events/152/india-women-tour-of-bangladesh-t20-series-2024/match/1492/4th-t20i',
 'https://www.bcci.tv/events/152/india-women-tour-of-bangladesh-t20-series-2024/match/1493/5th-t20i',
 'https://www.bcci.tv/events/150/icc-mens-t20-world-cup-2024/match/1399/1st-t20i',
 'https://www.bcci.tv/events/150/icc-mens-t20-world-cup-2024/match/1400/2nd-t20i',
 'https://www.bcci.tv/events/150/icc-mens-t20-world-cup-2024/match/1401/3rd-t20i',
 'https://www.bcci.tv/events/150/icc-mens-t20-world-cup-2024/match/1402/4th-t20i',
 'https://www.bcci.tv/events/147/india-tour-of-zimbabwe-2024/match/1349/1st-t20i',
 'https://www.bcci.tv/events/147/india-tour-of-zimbabwe-2024/match/1350/2nd-t20i',
 'https://www.bcci.tv/events/147/india-tour-of-zimbabwe-2024/match/1351/3rd-t20i',
 'https://www.bcci.tv/events/147/india-tour-of-zimbabwe-2024/match/1352/4th-t20i',
 'https://www.bcci.tv/events/147/india-tour-of-zimbabwe-2024/match/1353/5th-t20i',
 'https://www.bcci.tv/events/153/icc-womens-t20-world-cup-2024/match/1494/1st-t20i',
 'https://www.bcci.tv/events/153/icc-womens-t20-world-cup-2024/match/1495/2nd-t20i',
 'https://www.bcci.tv/events/153/icc-womens-t20-world-cup-2024/match/1496/3rd-t20i',
 'https://www.bcci.tv/events/153/icc-womens-t20-world-cup-2024/match/1497/4th-t20i']

In [28]:
Series_name = []
Place_name = []
Date_ = []
Time_ = []

In [30]:
for a in urls:
    driver.get(a)
    time.sleep(10)
    
    
    try:
        series_details = driver.find_element(By.XPATH, '//div[@class="tournament--name ng-binding ng-scope"][1]')
        Series_name.append(series_details.text)
    except NoSuchElementException as e:
        Series_name.append("--")   
        
        
    try:
        place_details = driver.find_element(By.XPATH, '//div[@class="matchVenue"]')
        Place_name.append(place_details.text)
    except NoSuchElementException as e:
        Place_name.append("--")
        
        
    
    try:
        date_details = driver.find_element(By.XPATH, '//div[@class="matchDate ng-binding ng-scope"]')
        Date_.append(date_details.text)
    except NoSuchElementException as e:
        Date_.append("--")
        
        
        
    
    try:
        time_details = driver.find_element(By.XPATH, '//div[@class="matchTm ng-binding"]')
        Time_.append(time_details.text)
    except NoSuchElementException as e:
        Time_.append("--")

In [31]:
print(len(Series_name))
print(len(Place_name))
print(len(Date_))
print(len(Time_))

15
15
15
15

In [32]:
df = pd.DataFrame({'Series name': Series_name, 'Place name': Place_name, 'Date': Date_, 'Time': Time_})
df

   Series name Place name Date Time
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14

### 3. Scrape the details of State-wise GDP of India from statisticstime.com.   Url = http://statisticstimes.com/   You have to find following details: 
### A) Rank   B) State   C) GSDP(18-19)- at current prices   D) GSDP(19-20)- at current prices   E) Share(18-19)   F) GDP( $ billion)   
Note: - From statisticstimes home page you have to reach to economy page through code.

In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\hp\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\hp\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\hp\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\hp\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
import selenium
import pandas as pd
from selenium import webdriver

import warnings
warnings.filterwarnings('ignore')

from selenium.webdriver.common.by import By
import time

In [3]:
driver = webdriver.Chrome()

In [4]:
driver.get("https://statisticstimes.com/")

In [7]:
economy = driver.find_element(By.XPATH, '//div[@class="dropdown"][2]')
economy.click()

In [8]:
INDIA = driver.find_element(By.XPATH, '/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
INDIA.click()

In [12]:
GDP = driver.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
GDP.click()

In [13]:
Rank = []
State = []
GSDP_at_current_prices1 = []
GSDP_at_current_prices2 = []
Share = []
GDP = []

In [15]:
rank_ = driver.find_elements(By.XPATH, '//table[@class="display dataTable"]/tbody/tr/td[1]')
for i in rank_:
    Rank.append(i.text)
    
    
    
    
state_ =  driver.find_elements(By.XPATH, '//table[@class="display dataTable"]/tbody/tr/td[2]')
for j in state_:
    State.append(j.text) 
    
    
    
    
gsdp1 =  driver.find_elements(By.XPATH, '//table[@class="display dataTable"]/tbody/tr/td[5]')
for k in gsdp1:
    GSDP_at_current_prices1.append(k.text) 
    
    
    
    
gsdp2 =  driver.find_elements(By.XPATH, '//table[@class="display dataTable"]/tbody/tr/td[10]')
for l in gsdp2:
    GSDP_at_current_prices2.append(l.text) 
    
    
    

share_ =  driver.find_elements(By.XPATH, '//table[@class="display dataTable"]/tbody/tr/td[6]')
for m in share_:
    Share.append(m.text)
    
    
    
    
gdp_ =  driver.find_elements(By.XPATH, '//table[@class="display dataTable"]/tbody/tr/td[7]')
for n in gdp_:
    GDP.append(n.text)

In [16]:
print(len(Rank))
print(len(State))
print(len(GSDP_at_current_prices1))
print(len(GSDP_at_current_prices2))
print(len(Share))
print(len(GDP))

66
66
66
33
66
66

In [19]:
df = pd.DataFrame({'Rank': Rank[:33], 'State': State[:33], 'GDPS AT CURRENT PRICES 21-22':GSDP_at_current_prices1[:33],
                  'GDPS AT CURRENT PRICES 11-12':GSDP_at_current_prices2[:33], 'Share': Share[:33], 'GDP': GDP[:33]})
df

,Rank,State,GDPS AT CURRENT PRICES 21-22,GDPS AT CURRENT PRICES 11-12,Share,GDP
0,1,Maharashtra,"3,108,022","2,027,971",13.17%,414.928
1,2,Tamil Nadu,"2,071,286","1,343,287",8.78%,276.522
2,3,Karnataka,"1,978,094","1,235,377",8.38%,264.080
3,4,Uttar Pradesh,"1,975,595","1,200,093",8.37%,263.747
4,5,Gujarat,"1,928,683","1,365,922",8.17%,257.484
5,6,West Bengal,"1,329,238","787,439",5.63%,177.456
6,7,Rajasthan,"1,193,489","727,805",5.06%,159.334
7,8,Andhra Pradesh,"1,148,471","722,727",4.87%,153.324
8,9,Telangana,"1,124,204","669,229",4.76%,150.084
9,10,Madhya Pradesh,"1,092,964","584,470",4.63%,145.913
10,11,Kerala,"934,542","578,057",3.96%,124.764
11,12,Delhi,"881,336","580,396",3.73%,117.660
12,13,Haryana,"868,905","544,317",3.68%,116.001
13,14,Odisha,"662,886","430,541",2.81%,88.497
14,15,Bihar,"650,302","399,930",2.76%,86.817
15,16,Punjab,"617,192","434,261",2.62%,82.397
16,17,Assam,"411,454","278,835",1.74%,54.930
17,18,Chhattisgarh,"410,525","280,609",1.74%,54.806
18,19,Jharkhand,"358,863","243,348",1.52%,47.909
19,20,Uttarakhand,"267,143","184,274",1.13%,35.664
20,21,Jammu & Kashmir,"193,352","119,174",0.82%,25.813
21,22,Himachal Pradesh,"172,162","124,770",0.73%,22.984
22,23,Goa,"84,266","55,342",0.36%,11.250
23,24,Tripura,"62,550","39,487",0.27%,8.351
24,25,Chandigarh,"46,096","30,587",0.20%,6.154
25,26,Puducherry,"43,810","27,131",0.19%,5.849
26,27,Meghalaya,"38,785","24,267",0.16%,5.178
27,28,Sikkim,"37,557","20,728",0.16%,5.014
28,29,Manipur,"36,594","20,515",0.16%,4.885
29,30,Arunachal Pradesh,"34,775","19,707",0.15%,4.643
30,31,Nagaland,"31,038","17,336",0.13%,4.144
31,32,Mizoram,"27,824","18,494",0.12%,3.715
32,33,Andaman & Nicobar Islands,"10,371","7,172",0.04%,1.385

### 4. Scrape the details of trending repositories on Github.com.    Url = https://github.com/    You have to find the following details:   
#### A) Repository title   B) Repository description   C) Contributors count   D) Language used   
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\hp\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\hp\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\hp\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\hp\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
import selenium
import pandas as pd
from selenium import webdriver

import warnings
warnings.filterwarnings('ignore')

from selenium.webdriver.common.by import By
import time

In [3]:
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException

In [4]:
driver = webdriver.Chrome()

In [5]:
driver.get("https://github.com/")

In [6]:
open_source = driver.find_element(By.XPATH, '/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
open_source.click()

In [7]:
trending = driver.find_element(By.XPATH, '/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a')
trending.click()

In [8]:
Repository_title = []
Repository_description = []
Contributors_count = []
Language_used = []

In [11]:
repository = driver.find_elements(By.XPATH, '//a[@class="Link"]')
for i in repository:
    Repository_title.append(i.text)
    
    
    
    
repository_desc = driver.find_elements(By.XPATH, '//p[@class="col-9 color-fg-muted my-1 pr-4"]')
for j in repository_desc:
    Repository_description.append(j.text)
    
    
    
    
count = driver.find_elements(By.XPATH, '//div[@class="f6 color-fg-muted mt-2"]/a[1]')
for k in count:
    Contributors_count.append(k.text)
    
    
    
    
language = driver.find_elements(By.XPATH, '//div[@class="f6 color-fg-muted mt-2"]/span[1]')
for l in language:
    Language_used.append(l.text)

In [12]:
print(len(Repository_title))
print(len(Repository_description))
print(len(Contributors_count))
print(len(Language_used))

25
25
25
25

In [13]:
df = pd.DataFrame({'Repository Title': Repository_title, 'Repository description': Repository_description, 
                   'Contributors count':Contributors_count,
                  'Language used':Language_used})
df

,Repository Title,Repository description,Contributors count,Language used
0,KindXiaoming / pykan,Kolmogorov Arnold Networks,"5,999",Jupyter Notebook
1,xM4ddy / OFGB,GUI Tool To Removes Ads From Various Places Ar...,"1,916",C#
2,rasbt / LLMs-from-scratch,"Implementing a ChatGPT-like LLM from scratch, ...","14,484",Jupyter Notebook
3,IvanGlinkin / CCTV,Close-Circuit Telegram Vision revolutionizes l...,636,JavaScript
4,karpathy / llm.c,"LLM training in simple, raw C/CUDA","18,002",Cuda
5,Blealtan / efficient-kan,An efficient pure-PyTorch implementation of Ko...,215,Python
6,lmstudio-ai / lms,LM Studio in your terminal,191,TypeScript
7,solana-labs / solana,"Web-Scale Blockchain for fast, secure, scalabl...","12,204",Rust
8,fastfetch-cli / fastfetch,"Like neofetch, but much faster because written...","4,683",C
9,pydantic / logfire,Uncomplicated Observability for Python and bey...,661,Python
10,Stirling-Tools / Stirling-PDF,#1 Locally hosted web application that allows ...,"23,407",Java
11,wandb / openui,OpenUI let's you describe UI using your imagin...,"6,914",TypeScript
12,reorproject / reor,Private & offline AI personal knowledge manage...,"4,808",TypeScript
13,systemdesign42 / system-design,A resource to help you learn system design.,"8,697",Built by
14,HVision-NKU / StoryDiffusion,Create Magic Story!,609,Jupyter Notebook
15,mlc-ai / web-llm,Bringing large-language models and chat to web...,"9,344",TypeScript
16,huggingface / candle,Minimalist ML framework for Rust,"13,573",Rust
17,MaaAssistantArknights / MaaAssistantArknights,《明日方舟》小助手，全日常一键长草！| A one-click tool for the d...,"11,913",C++
18,adrianhajdin / banking,Horizon is a modern banking platform for every...,326,TypeScript
19,Profluent-AI / OpenCRISPR,AI-generated gene editing systems,756,Built by
20,langgenius / dify,Dify is an open-source LLM app development pla...,"26,446",TypeScript
21,cpacker / MemGPT,Create LLM agents with long-term memory and cu...,"9,282",Python
22,Universidade-Livre / ciencia-da-computacao,🎓 Um caminho para a educação autodidata em Ciê...,"13,371",Built by
23,codecrafters-io / build-your-own-x,Master programming by recreating your favorite...,"259,575",Built by
24,tokio-rs / axum,Ergonomic and modular web framework built with...,"16,320",Rust

### 5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/  You have to find the following details:   
### A) Song name   B) Artist name   C) Last week rank   D) Peak rank   E) Weeks on board   
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [14]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\hp\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\hp\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\hp\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\hp\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [15]:
import selenium
import pandas as pd
from selenium import webdriver

import warnings
warnings.filterwarnings('ignore')

from selenium.webdriver.common.by import By
import time

In [16]:
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException

In [17]:
driver = webdriver.Chrome()

In [18]:
driver.get("https://www.billboard.com/")

In [19]:
chart = driver.find_element(By.XPATH, '/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a')
chart.click()

In [20]:
hot_100 = driver.find_element(By.XPATH, '/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div/div[2]/span/a')
hot_100.click()

In [21]:
Song_name = []
Artist_name = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

In [22]:
song = driver.find_elements(By.XPATH, '//li[@class="lrv-u-width-100p"]/ul/li/h3')
for i in song:
    Song_name.append(i.text)
    
    

artist = driver.find_elements(By.XPATH, '//li[@class="lrv-u-width-100p"]/ul/li[1]/span[1]')
for j in artist:
    Artist_name.append(j.text)
    
    
    
last_week = driver.find_elements(By.XPATH, '//li[@class="lrv-u-width-100p"]/ul/li[4]')
for k in last_week:
    Last_week_rank.append(k.text)
    
    
    
peak = driver.find_elements(By.XPATH, '//li[@class="lrv-u-width-100p"]/ul/li[5]')
for l in peak:
    Peak_rank.append(l.text)
    
    
    
week_onboard = driver.find_elements(By.XPATH, '//li[@class="lrv-u-width-100p"]/ul/li[6]')
for m in week_onboard:
    Weeks_on_board.append(m.text)
    
    
    Song name 
Artist name
Last week rank
Peak rank 
Weeks on board

In [23]:
print(len(Song_name))
print(len(Artist_name))
print(len(Last_week_rank))
print(len(Peak_rank))
print(len(Weeks_on_board))

100
100
100
100
100

In [24]:
df = pd.DataFrame({'Song name': Song_name, 'Artist name': Artist_name, 
                   'Last week rank':Last_week_rank,
                  'Peak rank ':Peak_rank,  'Weeks on board':Weeks_on_board })
df

,Song name,Artist name,Last week rank,Peak rank,Weeks on board
0,Fortnight,Taylor Swift Featuring Post Malone,-,1,1
1,Down Bad,Taylor Swift,-,2,1
2,I Can Do It With A Broken Heart,Taylor Swift,-,3,1
3,The Tortured Poets Department,Taylor Swift,-,4,1
4,"So Long, London",Taylor Swift,-,5,1
...,...,...,...,...,...
95,Us Vs. Them,$uicideBoy$,-,96,1
96,Wine Into Whiskey,Tucker Wetmore,84,77,5
97,Spin You Around (1/24),Morgan Wallen,89,24,13
98,Soak City,310babii,82,53,19
99,Selfish,Justin Timberlake,60,19,13

### 6. Scrape the details of Highest selling novels.   
### A) Book name   B) Author name   C) Volumes sold   D) Publisher   E) Genre   
Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [25]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\hp\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\hp\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\hp\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\hp\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [26]:
import selenium
import pandas as pd
from selenium import webdriver

import warnings
warnings.filterwarnings('ignore')

from selenium.webdriver.common.by import By
import time

In [27]:
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException

In [28]:
driver = webdriver.Chrome()

In [29]:
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [31]:
Book_name = []
Author_name = []
Volumes_sold = []
Publisher = []
Genre = []

In [33]:
Book= driver.find_elements(By.XPATH, '//table[@class="in-article sortable"]/tbody/tr/td[2]')
for i in Book :
    Book_name.append(i.text)
    
    
author = driver.find_elements(By.XPATH, '//table[@class="in-article sortable"]/tbody/tr/td[3]')
for j in author:
    Author_name.append(j.text)
    
    
volume_sold= driver.find_elements(By.XPATH, '//table[@class="in-article sortable"]/tbody/tr/td[4]')
for k in volume_sold :
    Volumes_sold.append(k.text)
    
    
publisher_ = driver.find_elements(By.XPATH, '//table[@class="in-article sortable"]/tbody/tr/td[5]')
for l in publisher_:
    Publisher.append(l.text)
    
    
genre_ = driver.find_elements(By.XPATH, '//table[@class="in-article sortable"]/tbody/tr/td[6]')
for m in genre_:
    Genre.append(m.text)

In [34]:
print(len(Book_name))
print(len(Author_name))
print(len(Volumes_sold))
print(len(Publisher))
print(len(Genre))

100
100
100
100
100

In [35]:
df = pd.DataFrame({'Book name': Book_name, 'Author name': Author_name, 
                   'Volumes sold':Volumes_sold,
                  'Publisher ':Publisher,  'Genre':Genre })
df

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

### 7. Scrape the details most watched tv series of all time from imdb.com.   
## Url = https://www.imdb.com/list/ls512407256/ You have to find the following details:   
### A) Name   B) Year span   C) Genre   D) Run time   E) Ratings   F) Votes

In [36]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\hp\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\hp\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\hp\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\hp\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [37]:
import selenium
import pandas as pd
from selenium import webdriver

import warnings
warnings.filterwarnings('ignore')

from selenium.webdriver.common.by import By
import time

In [38]:
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException

In [39]:
driver = webdriver.Chrome()

In [40]:
driver.get("https://www.imdb.com/list/ls512407256/")

In [41]:
Name = []
Year_span  = []
Genre = []
Run_time = []
Ratings = []
Votes= []

In [42]:
name_= driver.find_elements(By.XPATH, '//div[@class="lister-item-content"]/h3/a')
for i in name_ :
    Name.append(i.text)
    
    
year = driver.find_elements(By.XPATH, '//div[@class="lister-item-content"]/h3/span[2]')
for j in year:
    Year_span.append(j.text)
    
    
genre_ = driver.find_elements(By.XPATH, '//div[@class="lister-item-content"]/p/span[5]')
for k in genre_ :
    Genre.append(k.text)
    
    
time = driver.find_elements(By.XPATH, '//div[@class="lister-item-content"]/p/span[3]')
for l in time:
    Run_time.append(l.text)
    
    
rating_ = driver.find_elements(By.XPATH, '//div[@class="lister-item-content"]/div[1]/div[1]')
for m in rating_:
    Ratings.append(m.text)
    
    
    
vote = driver.find_elements(By.XPATH, '//div[@class="lister-item-content"]/p[4]/span[2]')
for n in vote:
    Votes.append(n.text)

In [43]:
print(len(Name))
print(len(Year_span))
print(len(Genre))
print(len(Run_time))
print(len(Ratings))
print(len(Votes))

100
100
100
100
100
100

In [44]:
df = pd.DataFrame({'Name': Name, 'Year Span': Year_span, 
                   'Genre':Genre,
                  'Run Time ':Run_time,  'Rating':Ratings, 'Votes': Votes})
df

,Name,Year Span,Genre,Run Time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",60 min,9.2,"2,286,995"
1,Stranger Things,(2016–2025),"Drama, Fantasy, Horror",60 min,8.7,"1,337,946"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",45 min,8.1,"1,083,094"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"315,705"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"276,432"
...,...,...,...,...,...,...
95,True Detective,(2014– ),"Crime, Drama, Mystery",60 min,8.9,"657,139"
96,Teen Wolf,(2011–2017),"Action, Drama, Fantasy",41 min,7.7,"163,363"
97,The OA,(2016–2019),"Drama, Fantasy, Mystery",60 min,7.8,"115,961"
98,The Simpsons,(1989– ),"Animation, Comedy",22 min,8.7,"436,224"
99,Desperate Housewives,(2004–2012),"Comedy, Drama, Mystery",45 min,7.6,"139,862"

### 8. Details of Datasets from UCI machine learning repositories.   Url = https://archive.ics.uci.edu/  You have to find the following details:   
### A) Dataset name   B) Data type   C) Task   D) Attribute type   E) No of instances   F) No of attribute G) Year   
Note: - from the home page you have to go to the Show All Dataset page through code.

In [45]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\hp\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\hp\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\hp\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\hp\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [46]:
import selenium
import pandas as pd
from selenium import webdriver

import warnings
warnings.filterwarnings('ignore')

from selenium.webdriver.common.by import By
import time

from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException

In [47]:
driver = webdriver.Chrome()

In [48]:
driver.get("https://archive.ics.uci.edu/")

In [49]:
dataset = driver.find_element(By.XPATH, '/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]')
dataset.click()

In [53]:
Dataset_name =[]
Data_type =[]
Task =[]
Attribute_type =[]
No_of_instances =[]
No_of_attribute =[]
Year =[]

In [59]:
expand_all = driver.find_element(By.XPATH, '/html/body/div/div[1]/div[1]/main/div/div[2]/div[1]/div/label[2]/div[2]/span[2]')
expand_all.click()

ElementClickInterceptedException: Message: element click intercepted: Element <span class="swap-on text-primary-content">...</span> is not clickable at point (639, 7). Other element would receive the click: <span class="swap-off text-primary-content">...</span>
  (Session info: chrome=124.0.6367.119)
Stacktrace:
	GetHandleVerifier [0x00007FF6CDB71502+60802]
	(No symbol) [0x00007FF6CDAEAC02]
	(No symbol) [0x00007FF6CD9A7CE4]
	(No symbol) [0x00007FF6CD9FE877]
	(No symbol) [0x00007FF6CD9FC344]
	(No symbol) [0x00007FF6CD9F980A]
	(No symbol) [0x00007FF6CD9F89E2]
	(No symbol) [0x00007FF6CD9EAE8B]
	(No symbol) [0x00007FF6CDA1AB7A]
	(No symbol) [0x00007FF6CD9EA7C6]
	(No symbol) [0x00007FF6CDA1AD90]
	(No symbol) [0x00007FF6CDA3A224]
	(No symbol) [0x00007FF6CDA1A923]
	(No symbol) [0x00007FF6CD9E8FEC]
	(No symbol) [0x00007FF6CD9E9C21]
	GetHandleVerifier [0x00007FF6CDE7411D+3217821]
	GetHandleVerifier [0x00007FF6CDEB60B7+3488055]
	GetHandleVerifier [0x00007FF6CDEAF03F+3459263]
	GetHandleVerifier [0x00007FF6CDC2B846+823494]
	(No symbol) [0x00007FF6CDAF5F9F]
	(No symbol) [0x00007FF6CDAF0EC4]
	(No symbol) [0x00007FF6CDAF1052]
	(No symbol) [0x00007FF6CDAE18A4]
	BaseThreadInitThunk [0x00007FF870B67344+20]
	RtlUserThreadStart [0x00007FF870CA26B1+33]

In [ ]:
Dataset name 
Data type 
Task 
Attribute type 
No of instances 
No of attribute 
Year

In [60]:
name= driver.find_elements(By.XPATH, '//h2[@class="truncate text-primary"]/a')
for i in name :
    Dataset_name.append(i.text)
    
    
type_ = driver.find_elements(By.XPATH, '//div[@class="col-span-3 flex items-center gap-2"][2]/span')
for j in type_:
    Data_type.append(j.text)
    
    
task_ = driver.find_elements(By.XPATH, '//div[@class="col-span-3 flex items-center gap-2"][1]/span')
for k in task_ :
    Task.append(k.text)
    
    
attribute_type_ = driver.find_elements(By.XPATH, '//table[@class="col-span-full my-2 table sm:col-start-2"]/tbody/tr/td[2]')
for l in attribute_type_:
    Attribute_type.append(l.text)
    

instance= driver.find_elements(By.XPATH, '//div[@class="col-span-3 flex items-center gap-2"][3]/span')
for m in instance:
    No_of_instances.append(m.text)
    
    
    
attribute = driver.find_elements(By.XPATH, '//table[@class="col-span-full my-2 table sm:col-start-2"]/tbody/tr/td[1]')
for n in attribute:
    No_of_attribute.append(n.text)
    
    
    
year = driver.find_elements(By.XPATH, '//table[@class="col-span-full my-2 table sm:col-start-2"]/tbody/tr/td[3]')
for a in year:
    Year.append(a.text)

In [61]:
print(len(Dataset_name))
print(len(Data_type))
print(len(Task))
print(len(Attribute_type))
print(len(No_of_instances))
print(len(No_of_attribute))
print(len(Year))

10
10
10
10
10
10
10

In [62]:
df = pd.DataFrame({'Dateset name': Dataset_name, 'Data Type': Data_type, 
                   'Task':Task,
                  'Attribute type':Attribute_type,  'No of instances':No_of_instances, 'No of attribute': No_of_attribute, 'Year':Year })
df

,Dateset name,Data Type,Task,Attribute type,No of instances,No of attribute,Year
0,Iris,Tabular,Classification,Real,150 Instances,Biology,7/1/1988
1,Heart Disease,Multivariate,Classification,"Categorical, Integer, Real",303 Instances,Health and Medicine,7/1/1988
2,Dry Bean,Multivariate,Classification,"Integer, Real",13.61K Instances,Biology,9/14/2020
3,Rice (Cammeo and Osmancik),Multivariate,Classification,Real,3.81K Instances,Biology,10/6/2019
4,Adult,Multivariate,Classification,"Categorical, Integer",48.84K Instances,Social Science,5/1/1996
5,Breast Cancer Wisconsin (Diagnostic),Multivariate,Classification,Real,569 Instances,Health and Medicine,11/1/1995
6,Raisin,Multivariate,Classification,"Real, Integer",900 Instances,Biology,8/14/2023
7,Wine,Tabular,Classification,"Integer, Real",178 Instances,Physics and Chemistry,7/1/1991
8,Wine Quality,Multivariate,"Classification, Regression",Real,4.9K Instances,Business,10/7/2009
9,Diabetes,"Multivariate, Time-Series",Classification,"Categorical, Integer",1 Instances,Health and Medicine,N/A